# Generated by Django 4.2.1 on 2023-06-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_plato_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='categoria',
            field=models.CharField(choices=[('V', 'Veganos'), ('D', 'Destacados'), ('N', 'Novedades'), ('G', 'Generales'), ('PC', 'Platos Caseros'), ('P', 'Pastas'), ('S', 'Sopas'), ('O', 'Ofertas'), ('CR', 'Comida Rapida')], max_length=80),
        ),
    ]
