# Generated by Django 4.2.1 on 2023-06-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_plato_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='categoria',
            field=models.CharField(choices=[('V', 'Veganos'), ('D', 'Destacados'), ('PC', 'Platos Caseros'), ('P', 'Pastas'), ('S', 'Sopas'), ('CR', 'Comida Rapida')], max_length=80),
        ),
    ]
